CREATE TABLE [dbo].[sqlserverdb](
	[id] [int] NOT NULL,
	[bigintType] [bigint] NULL,
	[binaryType] [binary](50) NULL,
	[bitType] [bit] NULL,
	[charType] [char](10) NULL,
	[dateType] [date] NULL,
	[datetimeType] [datetime] NULL,
	[datetime2Type] [datetime2](7) NULL,
	[datetimeoffsetType] [datetimeoffset](7) NULL,
	[decimalType] [decimal](18, 0) NULL,
	[floatType] [float] NULL,
	[geographyType] [geography] NULL,
	[geometryType] [geometry] NULL,
	[hierarchyidType] [hierarchyid] NULL,
	[imageType] [image] NULL,
	[intType] [int] NOT NULL,
	[moneyType] [money] NULL,
	[ncharType] [nchar](10) NULL,
	[ntextType] [ntext] NULL,
	[numericType] [numeric](18, 0) NULL,
	[nvarcharType] [nvarchar](50) NULL,
	[realType] [real] NULL,
	[smalldatetimeType] [smalldatetime] NULL,
	[smallintType] [smallint] NULL,
	[smallmoneyType] [smallmoney] NULL,
	[sql_variantType] [sql_variant] NULL,
	[textType] [text] NULL,
	[timeType] [time](7) NULL,
	[timestampType] [timestamp] NULL,
	[tinyintType] [tinyint] NULL,
	[uniqueidentifierType] [uniqueidentifier] NULL,
	[varbinaryType] [varbinary](50) NULL,
	[varcharType] [varchar](50) NULL,
	[xmlType] [xml] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
